### ISSUE TITLE
Fix Back Button on Mobile

### ISSUE THREAD

**Issue by dhuangg** [omou-org/front-end#104]
It's not sized properly on mobile right now
<img width="478" alt="Screen Shot 2019-09-12 at 6 50 41 PM" src="https://user-images.githubusercontent.com/12959959/64832301-3dc67780-d58e-11e9-859d-a6a695af5806.png">

**Comment by NeilAllavarpu** [comment]
Back Button should not be so tall on mobile:
<img width="309" alt="Screen Shot 2019-09-15 at 15 26 34" src="https://user-images.githubusercontent.com/13577797/64928437-4d7fcf00-d7cd-11e9-87e0-a2ac923bc4e4.png">
