### ISSUE TITLE
Responsive design for scheduler

### ISSUE THREAD

**Issue by NeilAllavarpu** [omou-org/front-end#118]
Example: Date looks a bit off-center on 13 inch screens.
Remember: Check to make sure various screen sizes will work (phone, tablet, laptop).

<img width="833" alt="Screen Shot 2019-09-16 at 12 09 51" src="https://user-images.githubusercontent.com/13577797/64996267-54bce080-d892-11e9-895b-3cca5ce40798.png">

**Comment by CalvinFronda** [comment]
Should be fixed in todays push.
