### ISSUE TITLE
Enrollment Endpoint Connection

### ISSUE THREAD

**Issue by dhuangg** [omou-org/front-end#168]
Currently course enrollments are pulling from the GET all students endpoint. this is an issues because not all students are loaded initially. Need to make individual GET student calls if student isn't in the list of 300 students pulled initially. 

All features relying on getting a student like this should be fixed. @jsflca2012 can you please look for all instances where we're pulling a parent or a student from the redux store in any Accounts or Registration feature? 

```const rows = course.roster.map((student_id) => {
    console.log(student_id, students);
    const student = students[student_id];
    const parent = parents[student.parent_id];
```

**Comment by dhuangg** [comment]
This needs to be done by the end of the week (11/30)

**Comment by dhuangg** [comment]
@NeilAllavarpu bump. the enrollment ep on the registration course page doesn't seem to be working again

**Comment by NeilAllavarpu** [comment]
As in #192, occurs for courses with no enrolled students. Will implement similar fix
