### ISSUE TITLE
Apply loading screen

### ISSUE THREAD

**Issue by dhuangg** [omou-org/front-end#169]
There are a couple of places where we need loading screens: 

- [ ] loading all users
- [x] loading all courses
- [ ] loading all search results
- [x] loading an account page

Have this done by the end of the week (11/30)

**Comment by dhuangg** [comment]
Need to update this to a loading icon instead of the penguin. Or make the penguin centered and smaller

**Comment by NeilAllavarpu** [comment]
Can this be closed or is there something still to do?
