### ISSUE TITLE
Make all user ID's in the top left of the profile heading component

### ISSUE THREAD

**Issue by dhuangg** [omou-org/front-end#171]
Right now the user ID's location isn't consistent. Change the student's profile heading

![Screen Shot 2019-11-25 at 2 55 34 PM](https://user-images.githubusercontent.com/12959959/69585119-a7ea9800-0f93-11ea-8f4c-706cd85145b4.png)
![Screen Shot 2019-11-25 at 2 55 07 PM](https://user-images.githubusercontent.com/12959959/69585120-a7ea9800-0f93-11ea-8e41-166bd4edda1d.png)
![Screen Shot 2019-11-25 at 2 54 50 PM](https://user-images.githubusercontent.com/12959959/69585121-a7ea9800-0f93-11ea-9710-bb803f7c3749.png)

**Comment by CalvinFronda** [comment]
#218
