### ISSUE TITLE
Display More Search Results

### ISSUE THREAD

**Issue by dhuangg** [omou-org/front-end#175]
## Background on Search API
@tigermli was able to add an extra "page" parameter in our search endpoint, you can see this currently used in our API request configuration (SearchResults.js line 66)
```const requestConfig = { params: { query: params.query, page: 1 }, headers: {"Authorization": `Token ${props.auth.token}`,} };```

**The "page" parameter in the API request gets the first 8 results that the backend finds.** Here are the rest of the account filters + the descriptions of how they work:
- profile: possible options below
  - student
  - instructor
  - parent, 
- grade: any number between 1 and 13
  - NOTE: if this is on, no instructor, parent, receptionist, or admin should be matched. 
- sort: (options below)
  - alpha: sort alphabetically by first name
  - desc: sort by id number (descending) 

Also feel free to view [this Airtable](https://airtable.com/tblKBsoAtlwvUE8wI/viwzY9WshIXLlV0hF?blocks=hide) for more descriptions of filters for courses.

@tigermli was also kind enough to create [this documentation](https://github.com/omou-org/front-end/wiki/Search-API-Documentation) for the search API!

### Making the API Call
I already wrote the redux actions + reducer to be able to call the search endpoint. You can update the search results by calling these 2 functions:
1. `props.searchActions.fetchSearchAccountQuery(requestConfig);`
2. `props.searchActions.fetchSearchCourseQuery(requestConfig);`

`requestConfig` you see in the parameters, is the same as the one as I mentioned earlier. Here's a refresher:
```const requestConfig = { params: { query: params.query, page: 1 }, headers: {"Authorization": `Token ${props.auth.token}`,} };```

**Bottom Line**: You can activate filters by changing the requestConfig variable under "params." Just add the param/filter you want, plus the value it should be. For example, I want to filter by grade so I only see grade 2 related results, I would adjust the requestConfig like this: 
```const requestConfig = { params: { query: params.query, page: 1, grade:2 }, headers: {"Authorization": `Token ${props.auth.token}`,} };```
NOTICE: I added a "grade:2" to the "params" object

Example 2: I want to see more than the first 8 results, I would adjust the requestConfig like this:
```const requestConfig = { params: { query: params.query, page: 2 }, headers: {"Authorization": `Token ${props.auth.token}`,} };```
NOTICE: I updated the "page" param to be 2 instead of 1, to get the next 8 results. 

## What Needs To Be Done
1. Display a "Keyboard_Right" arrow icon if a type of search result (i.e. "Account" or "Course") has more than 4 results
    - make sure to position this arrow icon to the right of the fourth result card. 
2. Implement a `displayMoreResults()` function. This function should be triggered when the arrow icon is clicked (i.e. `<MoreResultsIcon onClick = { displayMoreResults() } >`
    - There's 2 possibility for displaying more results: 1) we're on the first 4 results and we need to display the last 4 of the 8 original results we got or 2) we're on the last 4 results and we need to get the next 8 results by making another API call
      1) If we're on the first 4 results and we need to display the last 4 results, we just need to change this function that you wrote: `props.search.accounts.slice(0, 4).map((account) => ..some more code`. Instead of (0,4), we would want (5,8). Consider creating state variables and updating these state variables if this is the case.
      - NOTE: if you are creating state variables to control if we're splicing (0,4) or (5,8) results, make sure to have separate ones for account results vs. course results! 
      2) if we're on the last 4 results and we need to get the next 8 results, we need to do 2 steps: a) make an API for the next 8 results and b) reset the results we want to slice from (5,8) back to (0,4)
        a) Refer to Example 2 of the "Making the API Call," this is how we'll be able to get additional search results. Consider creating a state variable that is a counter for which page of search results we're on. 
        - NOTE: if the response/results array you're getting is an empty array after going to a new page of results (e.g. page:4 for the 4th page of results), that means that there's no more results, and we shouldn't display the arrow icon. 
        b) Similar to what we did for the first possibility so refer to that for the logic of changing (5,8) back to (0,4)

**Comment by CalvinFronda** [comment]
Hey i figured it out. If we are solving, if we need to go to the next page, we can do.

```
function display(count ,currentPage){
  let total = count/8;
  if(Math.ceil(total) > currentPage){
    return true;
  } else{
    return false
  }
}
```

So it takes the count, divides it by the amount of items we are trying to display. If the total is greater than the currentPage then we can go to the next page.

**Comment by dhuangg** [comment]
looks good. now do the equivalent for less results!

**Comment by dhuangg** [comment]
also rename "total" to "maxPages"

**Comment by CalvinFronda** [comment]
```function displayLess(incomingData,currentPage){
  let maxPages = Math.ceil(incomingData/8);
  if(maxPages >= currentPage && currentPage !== 1){
    return true
  }else {
    return false;
  }
}```

Made it more readable. So if we are checking if we need to go back, we need to check if we have reached the max page and that we aren't on page 1
