### ISSUE TITLE
Fix Course Results Only Spacing

### ISSUE THREAD

**Issue by dhuangg** [omou-org/front-end#176]
There's a lot of extra space when I only look for course. try to remove the extra space
![Screen Shot 2019-11-30 at 12 17 47 AM](https://user-images.githubusercontent.com/12959959/69897902-e91dd780-1306-11ea-98eb-eb12f538e360.png)

**Comment by CalvinFronda** [comment]
Did you fix it? It looks good to me, we can close this 😄 

<img width="1792" alt="Screen Shot 2020-02-05 at 10 04 23 PM" src="https://user-images.githubusercontent.com/40410706/73910211-86dfd680-4863-11ea-940d-49bee2891c74.png">
