### ISSUE TITLE
Registration Course Page not loading correctly 

### ISSUE THREAD

**Issue by dhuangg** [omou-org/front-end#180]
There's 2 issues that appear randomly/with no pattern: 
1) the notes endpoint somehow reduces the course object to just the notes
2) the FETCH_ENROLLMENT_SUCCESS action is only getting dispatched to "courseReducer.js" instead of both "courseReducer.js" and "enrollmentReducer.js" 

This is happening when you re-load any registrationCourse page

**Comment by NeilAllavarpu** [comment]
Should be fixed, reopen if it is not
