### ISSUE TITLE
Enrollment Hook Not Working

### ISSUE THREAD

**Issue by dhuangg** [omou-org/front-end#192]
Enrollment hook doesn't seem to be working. It's always loading. 
From Line 61 - 69 in StudentCourseViewer.js Once this is commented out, it works. likely because enrollment status isn't being updated. The server logs indicates a successful request is made.
if (!enrollments[studentID]) {
        if (hooks.isLoading(enrollmentStatus, courseStatus)) {
            return <Loading />;
        }

        if (hooks.isFail(enrollmentStatus, courseStatus)) {
            return "Error loading courses!";
        }
    }

**Comment by NeilAllavarpu** [comment]
Seems to only occur when the viewed student has no enrollments.
