### ISSUE TITLE
Category Posting Bug

### ISSUE THREAD

**Issue by dhuangg** [omou-org/front-end#194]
I think it's because this is a prop, so the hook isn't updating when the prop is updated, but you can't always see the posted category after you've added it even when its in redux.

**Comment by NeilAllavarpu** [comment]
Can you provide details on how to replicate this?

**Comment by dhuangg** [comment]
Hm I can't even replicate it myself. It used to be when you're posting a new category from this view below, the new category sometimes won't show up. I'll close this for now
![Screen Shot 2019-12-31 at 11 58 07 AM](https://user-images.githubusercontent.com/12959959/71632726-daa43380-2bc4-11ea-8e85-6adf0c44da9d.png)
