### ISSUE TITLE
Display Instructor Availability

### ISSUE THREAD

**Issue by dhuangg** [omou-org/front-end#206]
On the instructor's profile page as shown below, we want to include "business hours" to indicate the instructor's availability as well as the courses the instructor is currently teaching. Here are the todo's

## Add business hours
This will require you to 1) fetch the business hours 2) put them into fullcalendar.io 

Here's the [documentation](https://fullcalendar.io/docs/businessHours) on fullcalendar.io on their business hours. It's not very helpful on specifying syntax, but my guess is that you should be putting "businessHours" as an attribute of the component, and providing the array that they give in the example. Give that a shot for now. 

## Display courses the instructor is teaching for the week
This will require you to fetch both the classes and tutoring courses that the instructor is teaching for the current week. In other words, fetch all the sessions in a week by using the scheduler endpoint: 
`http://localhost:8000/scheduler/session/?time_frame=day&view_option=class&time_shift=0` 
- **time_frame**: when you want the sessions. Day will give you all the sessions on the day you call the end point. Example: I'm calling the endpoint today with the ""day" filter, so I'll get all the sessions for today. 
- **view_option**: what kinds of courses do you want to see. You can put "class" or "tutoring", but not both. Note: small groups are considered classes so you'll be able to get both classes and small groups when you have the "class" filter on.
- **time_shift**: this will allow you to get + / - the number of time_frames you indicate. For example: `time_shift=1` with `time_frame=day` will get me all the sessions tomorrow. `time_shift=2` with `time_frame=week` will get me a week's worth of sessions, 2 weeks from today. `time_shift=-1` with `time_frame=day` will get me all of tomorrow's sessions

Currently, the get session endpoint doesn't support filtering by instructor/getting both types of sessions (classes + tutoring) so you'll need to do this on the frontend. 

Once you've fetched all the relevant sessions, pass them to the "events" param in the FullCalendar component.

**Comment by dhuangg** [comment]
@NeilAllavarpu the scheduler endpoint actually can give you all of the sessions as long as you don't specify the view_option or you give view_option something other than "class" or "tutoring"

**Comment by dhuangg** [comment]
Include this component on the session view page to the right of the session information. 

Move the enrolled students to below the instructor. 

![Screen Shot 2020-01-08 at 7 14 07 PM](https://user-images.githubusercontent.com/12959959/72035073-aaefce00-324b-11ea-8805-476567904680.png)

**Comment by NeilAllavarpu** [comment]
What still needs to be done for this?

**Comment by dhuangg** [comment]
are we showing all the courses the instructor is teaching and their business hours?

**Comment by dhuangg** [comment]
@NeilAllavarpu Use this new instructor availability endpoint 
<img width="676" alt="Screen Shot 2020-02-26 at 10 07 20 PM" src="https://user-images.githubusercontent.com/12959959/75416886-71028600-58e4-11ea-816b-6429dd50286a.png">
