### ISSUE TITLE
Account/User/ Not Successful

### ISSUE THREAD

**Issue by dhuangg** [omou-org/front-end#210]
When the user first logs in, the `fetchUserStatus()` action dispatcher is called. When the dispatcher is called in App.js, the token hasn't loaded yet in redux/localStorage. Code in question is here (App.js line 16 - 21)

```
const dispatch = useDispatch();
    const token = useSelector(({auth}) => auth.token) || localStorage.getItem("authToken");
    const bound = useMemo(() => bindActionCreators(authActions, dispatch), [dispatch]);
    useEffect(() => {
        bound.fetchUserStatus(token);
    }, [bound, token]);
```

**Comment by dhuangg** [comment]
can't replicate now. will remove from milestone

**Comment by NeilAllavarpu** [comment]
Closing for now
