### ISSUE TITLE
Link Enrollments row to Session View

### ISSUE THREAD

**Issue by dhuangg** [omou-org/front-end#213]
This row
![Screen Shot 2020-01-08 at 7 13 18 PM](https://user-images.githubusercontent.com/12959959/72034835-feade780-324a-11ea-873d-e819596bdc29.png)

Links to its corresponding session ("/scheduler/view-session/student_id?/session_id/instructor_id")
![Screen Shot 2020-01-08 at 7 14 07 PM](https://user-images.githubusercontent.com/12959959/72034859-138a7b00-324b-11ea-9d6b-adbb4bc63fa6.png)

**Comment by CalvinFronda** [comment]
Is there a way to get the sessionID & instructorID in the courseSessionStatus page? I know when we make the sessions it is created in that scheduler component and it stays there. 
Also the route is (/scheduler/view-session/:course_id/:session_id/:instructor_id").

**Comment by dhuangg** [comment]
There is - look for where we're displaying each session row, you should be able to get the session ID from there. We're also displaying the instructor's name at the top of the page so you should be able to find the instructor id somewhere near there. 

Instructor ID example: line 426 courseSessionStatus.js
Session ID example: starts at line 303 courseSessionStatus.js

**Comment by NeilAllavarpu** [comment]
Should this link back to the home page for non-tutoring classes?

**Comment by CalvinFronda** [comment]
I linked courses to the course view in registration. I think thats a better option than linking to homepage.

**Comment by dhuangg** [comment]
I agree. this is a good change.
