### ISSUE TITLE
Course Session Status Breaks with no sessions

### ISSUE THREAD

**Issue by dhuangg** [omou-org/front-end#226]
## Steps to recreate bug
When an enrollment is created without any sessions, and the user goes to an enrollment page. The page will display the error below. 

![Screen Shot 2020-01-22 at 1 50 26 PM](https://user-images.githubusercontent.com/12959959/72939490-d1b90480-3d21-11ea-9716-9a6eb7ad030b.png)

## Background
There's 2 points of failures here:
1. The frontend is unable to make a POST to payment/payment/ so no sessions are generated
2. The backend won't generate sessions (for now) if there are no payments

Regardless, we need to be able to handle this type of error on the frontend on the enrollment view (CourseSessionStatus.js) 

If we detect that after line 169 in CourseSessionStatus.js doesn't have any items, then we shouldn't perform the "reduce" function on it.

**Comment by dhuangg** [comment]
NOTE: if there's nothing in the CourseSessions array, display the <NoListAlert/> component. Be sure to import it. It's a grey alert box that allows you to say that ___ list has no items.

**Comment by gglinoga** [comment]
@dhuangg @jerrylinew Remember to discuss

**Comment by dhuangg** [comment]
similar issue with production data. Can't do anything until discussion. will close this ticket for now
