### ISSUE TITLE
Fixing column spacing

### ISSUE THREAD

**Issue by dhuangg** [omou-org/front-end#229]
## Design Ticket
As a design ticket, these tickets can only be closed if you:

1. Merged with master
2. Confirmed with the designer listed on the ticket.
To confirm with the designer, either a) send screenshot as proof of fix, or b) set-up a call with the designer to get verbal confirmation.

**Designer** Gaby
<img width="1544" alt="Screen Shot 2020-01-23 at 11 54 55 AM" src="https://user-images.githubusercontent.com/12959959/73018974-83fed380-3dd7-11ea-8884-80b1fc3ce023.png">
<img width="1544" alt="Screen Shot 2020-01-23 at 11 48 33 AM" src="https://user-images.githubusercontent.com/12959959/73018975-83fed380-3dd7-11ea-98ff-df5da1840b42.png">

**Comment by CalvinFronda** [comment]
Hi Gaby, Please check the screen shots and advice if it is acceptable. 

I think this one is good.
<img width="1792" alt="Screen Shot 2020-02-04 at 10 10 23 PM" src="https://user-images.githubusercontent.com/40410706/73815598-43ba3080-479b-11ea-9d07-644af9f3729e.png">

Do you think the status column is too far to the left? 
<img width="1792" alt="Screen Shot 2020-02-04 at 10 10 37 PM" src="https://user-images.githubusercontent.com/40410706/73815701-94ca2480-479b-11ea-88c5-80920a3d2236.png">

**Comment by gabriellachan** [comment]
Hi Calvin! I think the first one's columns look good. Since both of them have similar types of column labels/data, I think the second one should look like the first one. So shifting the Day, Time, and Status columns to line up with how the first one looks.

**Comment by CalvinFronda** [comment]
Hi @gabriellachan, Let me know if I can push this up! 

<img width="1792" alt="Screen Shot 2020-02-05 at 9 48 29 PM" src="https://user-images.githubusercontent.com/40410706/73909420-7a5a7e80-4861-11ea-8c75-2e71275c17b7.png">

<img width="1792" alt="Screen Shot 2020-02-05 at 9 48 34 PM" src="https://user-images.githubusercontent.com/40410706/73909429-7fb7c900-4861-11ea-9ef1-45d74aa75aee.png">

**Comment by gabriellachan** [comment]
Looks great!
