### ISSUE TITLE
Accounts headers inconsistent between tabs

### ISSUE THREAD

**Issue by katiebelleho** [omou-org/front-end#236]
# Design Ticket

**Designer:** Katie 

 **Issue:** Table header spacing is inconsistent between the different tabs (all, parent, student, receptionist, etc). Header/column spacing on each tab should be consistent with what's on the Receptionist tab. 

![image](https://user-images.githubusercontent.com/60498283/73518286-bb124d80-43b2-11ea-9688-2f0e4e9e7ee1.png)

![image](https://user-images.githubusercontent.com/60498283/73518036-17c13880-43b2-11ea-82de-c866d4d83af5.png)
![image](https://user-images.githubusercontent.com/60498283/73518066-2a3b7200-43b2-11ea-81b6-16ed73ff1966.png)

**Comment by CalvinFronda** [comment]
@jsflca2012 @dhuangg So i think the issue here is that when a field is left blank, the size of the table gets smaller. I'm trying to look for a way to keep each table item a static size so they will be aligned on all tabs. If anyone finds anything lmk.
