### ISSUE TITLE
Inaccurate page heading when editing profile

### ISSUE THREAD

**Issue by katiebelleho** [omou-org/front-end#238]
# Design

**Designer:** Katie

**Issue:** When clicked on "Edit Profile", redirects to editing page but heading says "Course Registration Confirmation". Should say either "Edit Profile" or "Teacher Account" .

![image](https://user-images.githubusercontent.com/60498283/73521725-9a9ac100-43bb-11ea-8a99-3a3b9601f384.png)

**Comment by NeilAllavarpu** [comment]
Fixed the bug for most forms, notify me if there are any titles still inaccurate.
