### ISSUE TITLE
Registration tutoring subject cards border color

### ISSUE THREAD

**Issue by katiebelleho** [omou-org/front-end#240]
# Design Ticket

**Designer:** Katie

**Issue:** The cards should only have the blue border when hovered over (similar to the Course view cards). Sorry my figma frame was misleading, please refer back to figma witht updated design. 

![image](https://user-images.githubusercontent.com/60498283/73600244-274f9700-4502-11ea-93b7-ca04422cb739.png)

**Comment by NeilAllavarpu** [comment]
<img width="1280" alt="Captura de Pantalla 2020-03-01 a la(s) 15 41 59" src="https://user-images.githubusercontent.com/13577797/75636399-385bf880-5bd3-11ea-88b4-5d44e6c77f5b.png">
@katiebelleho

**Comment by katiebelleho** [comment]
@NeilAllavarpu 

border looks good! but just want to reiterate the tutoring catalog should be displaying general subjects available (from the screenshot, it looks like its feeding in the actual tutoring sessions?)

**Comment by NeilAllavarpu** [comment]
Yeah, that change is in a separate ticket.
