### ISSUE TITLE
Display Session Payment Status

### ISSUE THREAD

**Issue by dhuangg** [omou-org/front-end#254]
## Background
We need to display the session payment status in 3 places. These backend tickets describe where:
1. [Course Session Status View / Enrollment View](https://github.com/omou-org/mainframe/issues/44)
2. Course list view
![Screen Shot 2020-01-16 at 3 44 13 PM](https://user-images.githubusercontent.com/12959959/74299598-08bb7e00-4d02-11ea-8668-a3789275c106.png)
3. [Session View](https://user-images.githubusercontent.com/12959959/72685615-bee3cd00-3aa0-11ea-9999-57a13b4a2f80.png)

## Development
We'll be using the new enrollment endpoint which will be providing us with 2 new pieces of data: 
1. num_sessions - given to us in enrollment. Sessions remaining
2. Last_paid_session - datetime on enrollment
- [x] Create a function named `setPaymentStatus()` in a util file where input is the last_paid_session (a date), session_date (a date), and num_sessions. 
  - First the function should compare if the session_date is before, on, or after the last_paid_session date.
    - If session_date is before or on last_paid_session date: the function should return "Paid"
    - If the session_date is after last_paid_session date and num_sessions is not a whole number (i.e. there's a session that's partially paid for): the function should return "Partially Paid"
    - If session_date is after last_paid_session date: the function should return "Unpaid"
- [x] On courseSessionView.js, for each session, use the `setPaymentStatus()` function we created previously to determine if its "Paid" "Partially Paid" or "Unpaid". Also color the sessions as such: Paid = Green, Partially Paid = Orange, Unpaid = Red
- [x] On StudentCourseView.js, for each course, display num_sessions. If num_sessions > 3, the circle background color should be green. If 0 < num_sessions < = 3, the color should be orange. If num_sessions < 0, the color should be red.
- [x] On DisplaySessionView.js, use the `setPaymentStatus()` function to determine if the current session is paid for. 
  - Create a new field called "Session Payment Status" in its own row above "Subject" and "Room"
  - If the session is paid for, then put a green circle icon next to the number of paid sessions left (num_sessions) if num_sessions > 3. If 0 < num_sessions <= 3, then put an orange circle icon
  - If the session is not paid for, then put a red circle icon next to the number of paid sessions left

**Comment by NeilAllavarpu** [comment]
Made the function on branch `session-payment-status`.

**Comment by NeilAllavarpu** [comment]
For courseSessionStatus.js, each session already has a `status` attribute of paid or not - do we use our function, or that?

**Comment by NeilAllavarpu** [comment]
Also, how do I get the last paid session in DisplaySessionView.js?

**Comment by dhuangg** [comment]
the new enrollment endpoint should be giving us 3 new fields: 1) enrollment balance 2) last paid session date 3) num paid sessions. talk to @jerrylinew for more details. our current frontend doesnt use these new attributes from the enrollment endpoint and does not accurately reflect the payment status of a session

**Comment by dhuangg** [comment]
Refer to Enrollment documentation here: https://github.com/omou-org/mainframe/wiki/Enrollment-Documentation
