### ISSUE TITLE
Fixing Course Pages

### ISSUE THREAD

**Issue by jsflca2012** [omou-org/front-end#256]
Currently course pages looks like a mess, needs to be fixed to look like design.
What the page looks like right now:
![image](https://user-images.githubusercontent.com/52120602/74388563-8f2e9900-4db0-11ea-912e-324432d9de81.png)
How it should look:
![image](https://user-images.githubusercontent.com/52120602/74388632-b84f2980-4db0-11ea-82d5-baa0578502b9.png)

**Comment by dhuangg** [comment]
Good issue. Also use the NoListAlert component if there are no students. Look at NoListAlert.js
