### ISSUE TITLE
Migrating to Moment JS

### ISSUE THREAD

**Issue by dhuangg** [omou-org/front-end#298]
## Background
JS Dates suck. 

## Development
- [ ] Add the [react-moment](https://www.npmjs.com/package/react-moment) library
- [ ] Reference this quick search result text file of all the instances of "new Date" as the to-do list of what to change
[date_results_report.txt](https://github.com/omou-org/front-end/files/4333231/report.txt)
- [ ] Adjust everything to be using Moment JS

**Comment by NeilAllavarpu** [comment]
[Reference spreadsheet](https://docs.google.com/spreadsheets/d/1eSCkwwBsBR6CEjEF8kY6LpUXnB5IYHNbq8EuAL9nYnY/edit?usp=sharing)
