### ISSUE TITLE
Create test data

### ISSUE THREAD

**Issue by dhuangg** [omou-org/front-end#31]
Based on the data models, create test data for: 
- [x] student list
- [x] teacher list
- [x] parents list
- [x] course list
- [ ] categories list
- [ ] etc.

Reach out to @jerrylinew for any questions

**Comment by dhuangg** [comment]
Reference these links to see what needs to be filled in for test data: 
- [User accounts](https://github.com/omou-org/mainframe/blob/master/account/models.py) Be sure to take into account the base User class
- [Courses](https://github.com/omou-org/mainframe/blob/master/course/models.py)

**Comment by dhuangg** [comment]
Make the test data in excel first based off the models, then translate them into JSON objects in `initialState.js`

**Comment by dhuangg** [comment]
@jerrylinew do you have models for categories that @ryanliou02 can reference?

**Comment by ryanliou02** [comment]
https://docs.google.com/spreadsheets/d/1kjw--9xXK0hDznDU4GrYW0UybXr4oI71dymmLRfDC5k/edit#gid=1561449403
