### ISSUE TITLE
Change "Current Day" Background color to Omou Blue

### ISSUE THREAD

**Issue by dhuangg** [omou-org/front-end#353]
As per Selina's comments: 
> "Why the yellow background for Day view? Looks like the whole page is selected and does not look clean"

as well as

> "In Week/Month view, I would recommend using the light Sky blue color to indicate the current day to be consistent with Omou’s style guides and branding"

Change it to the Omou blue: `#43b5D9` 
Example of how to change the background color of the "Today" view: http://jsfiddle.net/z8Jfx/7/

**Comment by CalvinFronda** [comment]
Can we close this ticket? Remember we talked about how the colors don't really go with the background.

**Comment by dhuangg** [comment]
can you try a couple of versions? like a lighter/more opaque omou blue?
then paste the different version on the design channel to discuss
