### ISSUE TITLE
Clean up Instructor Account Button Positioning

### ISSUE THREAD

**Issue by dhuangg** [omou-org/front-end#362]
As per Selina's comment
> Buttons in the header look messy, not properly aligned
<img width="626" alt="Screen Shot 2020-04-26 at 8 27 30 PM" src="https://user-images.githubusercontent.com/12959959/80331246-612bf300-87fc-11ea-87f6-fcd9fd73ddad.png">

**Comment by clam1987** [comment]
Closing this issue because it looks fine the alignment is fixed on production.
![24772e0e8757c846f4182ad052cc95b5](https://user-images.githubusercontent.com/48064335/81128944-8bb23600-8ef7-11ea-9b4a-4ba33a553cfe.png)
