### ISSUE TITLE
Typography Changes to "No results found" page

### ISSUE THREAD

**Issue by dhuangg** [omou-org/front-end#373]
Per Selina's comments:
<img width="532" alt="Screen Shot 2020-04-28 at 7 25 23 PM" src="https://user-images.githubusercontent.com/12959959/80555749-06be9e00-8986-11ea-83f8-728723819f35.png">

**Comment by CalvinFronda** [comment]
let me know if this is okay. 
<img width="1351" alt="Screen Shot 2020-05-09 at 5 23 59 PM" src="https://user-images.githubusercontent.com/40410706/81488141-e0b4bb80-9219-11ea-9845-d20b4eb384b2.png">

**Comment by dhuangg** [comment]
looks good 👍 put it into a PR
