### ISSUE TITLE
Add a warning for any navigation away from a form

### ISSUE THREAD

**Issue by NeilAllavarpu** [omou-org/front-end#38]
Currently, clicking on any of the tabs in the side bar will leave a form without a warning to save changes, as would happen if the back button is clicked. There should always be a warning before leaving an incomplete form.

**Comment by dhuangg** [comment]
https://medium.com/@michaelchan_13570/using-react-router-v4-prompt-with-custom-modal-component-ca839f5faf39

make a custom one if there's time

**Comment by dhuangg** [comment]
prompt tag (react routes) only appears when editing the form. Doesn't appear on the submission page.
