### ISSUE TITLE
A08: Registration Flow

### ISSUE THREAD

**Issue by tigermli** [omou-org/front-end#396]
The receptionist can currently register new students/parents/classes through the registration catalog. This issue seeks to improve several slow-points:

**Todo**

1. **Select Parent Button**
Everything is competing with each other. Make it larger than the "New Student" button and lighter blue. Maybe Shadowing.

Example:

<img width="188" alt="Screen Shot 2020-06-06 at 9 24 56 PM" src="https://user-images.githubusercontent.com/11560193/83960299-2cb84780-a83c-11ea-9adb-fe60eab27fa3.png">

2. **New Student** and **Register ** buttons
Register is vague. Can mean register student as well. Rename both to "Register Student" and "Register Course". Same positions.

**Comment by jsflca2012** [comment]
I think it looks awkward with box shadowing since it is the only button on the page that is shadowed.
