### ISSUE TITLE
A017 - Note tab badge not updating with new number of important notes

### ISSUE THREAD

**Issue by dhuangg** [omou-org/front-end#451]
A017
Note Tab Badge not updating with new number of important notes
Bug found by: Daniel
Teams link: https://teams.microsoft.com/l/message/19:77d621b48fd54d03ba7155385d33cb54@thread.skype/1596234138688?tenantId=4757b031-c3cc-4b2a-ac2c-a2ef4731ed22&groupId=7f2d402f-bd5b-4f3d-875f-fb78e2889c1a&parentMessageId=1596234138688&teamName=Omou&channelName=Defects&createdTime=1596234138688

**Comment by pswk1** [comment]
@dhuangg @CalvinFronda 
Tagging here because Dahl tab migration (particularly Notes) is waiting on REST to GraphQL migration in Accounts &  EnrollmentView
