### ISSUE TITLE
A018 - Create tuition rules can't load course categories

### ISSUE THREAD

**Issue by dhuangg** [omou-org/front-end#452]
A018
Create Tuition Rules can't load course categories
Bug found by: Mat
Teams link: https://teams.microsoft.com/l/message/19:77d621b48fd54d03ba7155385d33cb54@thread.skype/1596250372836?tenantId=4757b031-c3cc-4b2a-ac2c-a2ef4731ed22&groupId=7f2d402f-bd5b-4f3d-875f-fb78e2889c1a&parentMessageId=1596250372836&teamName=Omou&channelName=Defects&createdTime=1596250372836

**Comment by CalvinFronda** [comment]
Fixed when cache is cleared.
