### ISSUE TITLE
A027 - Improper label to parent search in add student form

### ISSUE THREAD

**Issue by dhuangg** [omou-org/front-end#459]
A027
Improper label to Parent Search in Add Student form
Bug found by: Daniel
Teams link: https://teams.microsoft.com/l/message/19:77d621b48fd54d03ba7155385d33cb54@thread.skype/1596253270314?tenantId=4757b031-c3cc-4b2a-ac2c-a2ef4731ed22&groupId=7f2d402f-bd5b-4f3d-875f-fb78e2889c1a&parentMessageId=1596253270314&teamName=Omou&channelName=Defects&createdTime=1596253270314

**Comment by andrewjknapp** [comment]
Autocomplete components in m-ui have a prop called noOptionsText. This displays whatever string you give it when no options are available. In FormFormats.js on line 437 we call the parentSelect function which returns a DataSelect component from Fields.js. This DataSelect component returns an Autocomplete component. This is the target that we want to add the noOptionsText prop to. To accomplish this we can add the prop "noOptionsText={"No parents available"}" the DataSelect component created in the parentSelect function on line 365 of FormFormats.js. 
We can do this whenever the DataSelect component is called and add in whatever text we want to fit the field. DataSelect components are also made in categorySelect (line 388 FormFormats.js), and in schoolSelect (line 406 FormFormats.js). For each of these we can add the noOptionsText with whatever phrase sounds best.
