### ISSUE TITLE
A034 - Discounts display an error when there are no discounts stored

### ISSUE THREAD

**Issue by dhuangg** [omou-org/front-end#465]
A034
Discounts display an error when there are no discounts stored
Bug found by: Ryan
Teams link: https://teams.microsoft.com/l/message/19:77d621b48fd54d03ba7155385d33cb54@thread.skype/1596306982152?tenantId=4757b031-c3cc-4b2a-ac2c-a2ef4731ed22&groupId=7f2d402f-bd5b-4f3d-875f-fb78e2889c1a&parentMessageId=1596306982152&teamName=Omou&channelName=Defects&createdTime=1596306982152

**Comment by CalvinFronda** [comment]
Fixed when cache is cleared.
