### ISSUE TITLE
A045 - Inflexible phone number regex

### ISSUE THREAD

**Issue by dhuangg** [omou-org/front-end#474]
A045
Inflexible Phone number regex
Bug found by: Mat
Teams link: https://teams.microsoft.com/l/message/19:77d621b48fd54d03ba7155385d33cb54@thread.skype/1596308749232?tenantId=4757b031-c3cc-4b2a-ac2c-a2ef4731ed22&groupId=7f2d402f-bd5b-4f3d-875f-fb78e2889c1a&parentMessageId=1596308749232&teamName=Omou&channelName=Defects&createdTime=1596308749232

**Comment by andrewjknapp** [comment]
On line 173 of FormFormats.js this is the regex used to validate the incoming phone numbers /\d{3}-?\d{3}-?\d{4}?/u. This allows
the forms: 1112223333, 111-2223333, and 111-222-3333.
We could replace that with a more accepting regex /(\d{3}[- ]?\d{3}[- ]?\d{4}?)|([(]\d{3}[)][- ]?\d{3}[-]?\d{4}?)/ which accepts the above values along with 111 222 3333 and (111) 222-3333, and any combination of a single space, dash, or no space between the groups of numbers. This would allow the user to enter in any of these commonly used phone number formats.

Alternatively we could integrate another npm module to mask the input to default to the format that we want. 
Regex is the easy quick fix, masking is the more involved, but in terms of user experience better choice.

**Comment by dhuangg** [comment]
that sounds good - can you take screenshots of a couple of potential phone numbers with the input field?
