### ISSUE TITLE
A071 - Export icon doesn't work on admin portal

### ISSUE THREAD

**Issue by dhuangg** [omou-org/front-end#498]
A071
Export icon doesn't work on Admin Portal
Bug found by: Gina
Teams link: https://teams.microsoft.com/l/message/19:77d621b48fd54d03ba7155385d33cb54@thread.skype/1596319895080?tenantId=4757b031-c3cc-4b2a-ac2c-a2ef4731ed22&groupId=7f2d402f-bd5b-4f3d-875f-fb78e2889c1a&parentMessageId=1596319895080&teamName=Omou&channelName=Defects&createdTime=1596319895080

**Comment by rgedwill** [comment]
I removed it a little while ago - did we want to add support for this? It was combined with the issue that mentioned the delete button not working

**Comment by rgedwill** [comment]
Closing...was resolved in #539
