### ISSUE TITLE
Edit Session Registration Information

### ISSUE THREAD

**Issue by dhuangg** [omou-org/front-end#51]
- [ ] on the student's row on a `RegistrationCourse.js` table, make the pencil/edit icon lead to a form filled with the student's registration information. make sure to separate out the edit logic (i.e. filling in with existing data) out from the `form.js` component.
- [ ] make the route for the form w/ the student's registration information. make sure the route is protected.
- [ ] onClick of the finish button, have an alert to confirm changes
- [ ] replace the finish button with "Update Registration" text

**Comment by dhuangg** [comment]
This can't be completed until #63 is complete

**Comment by NeilAllavarpu** [comment]
Is this ticket still relevant?

**Comment by dhuangg** [comment]
this is a de-prioritized ticket. we can still leave it open but no need to
address it
