### ISSUE TITLE
Account row link - need to remove underline

### ISSUE THREAD

**Issue by dhuangg** [omou-org/front-end#678]
We need to remove the underline on the account row
<img width="1638" alt="Screen Shot 2021-01-18 at 9 36 09 PM" src="https://user-images.githubusercontent.com/12959959/104992153-40807a80-59d5-11eb-9401-5fc657939af8.png">

**Comment by andrewjknapp** [comment]
Temp solution, added text-decoration: none to "a" in theme.scss. Added to demo branch. Unsure if this affects other areas of Omou, but this works for the demo.
