### ISSUE TITLE
Edit Account under Profile View Styling

### ISSUE THREAD

**Issue by dhuangg** [omou-org/front-end#683]
For some reason the entire row shifts down when you hover over the edit icon.

https://user-images.githubusercontent.com/12959959/104994679-c43c6600-59d9-11eb-85eb-65ee98be206d.mov

# Development ToDo's
- [x] Make it so the row doesn't shift when the dropdown appears. Merge this to development
- [x] Make this so you open the dropdown on click instead of hover. Merge this to development
- [x] Should the dropdown be styled like this? This is what i'm seeing on Figma. may want to check with @katiebelleho or Gaby. When complete also merge this into development
![Screen Shot 2021-01-18 at 10 12 00 PM](https://user-images.githubusercontent.com/12959959/104994914-3f058100-59da-11eb-9bcb-bdb796caae41.png)
- [x] Remove the "Reset Password" option. merge into EAP_Jon_Demo

**Comment by andrewjknapp** [comment]
Design notes, move edit icon to right have edit options show underneath edit icon.
