### ISSUE TITLE
Highlight Account tab when you're in a user profile view

### ISSUE THREAD

**Issue by dhuangg** [omou-org/front-end#692]
<img width="1677" alt="Screen Shot 2021-01-24 at 11 08 38 PM" src="https://user-images.githubusercontent.com/12959959/105672393-2d6c1f80-5e99-11eb-85c6-7f1299082cc4.png">

**Comment by dhuangg** [comment]
@CalvinFronda take a look at the match object in react router https://reactrouter.com/web/api/match

**Comment by CalvinFronda** [comment]
Here is the changes on NavigationContainer.js 

```
 isActive={(match, location) =>
                                match?.url || //changed isExact to url
                                (NavItem.name === 'Dashboard' &&
                                    location.pathname === '/')
                            }
```
