### ISSUE TITLE
Search bar for courses and users in the header

### ISSUE THREAD

**Issue by NeilAllavarpu** [omou-org/front-end#70]
See the [figma](https://www.figma.com/file/dRC8BuvcPe5KcA7NFlmck01T/Omou?node-id=0%3A1) for design. Should have filters to search by different properties of courses and users

**Comment by dhuangg** [comment]
2 parts to this ticket. Fuzzy search and API endpoint search. 

Implement Fuzzy search on the frontend. Feel free the use the React Select component. Be sure to search through relevant data. Refer to screenshot for reference. (ticket continued below)
![Screen Shot 2019-08-21 at 11 38 12 PM](https://user-images.githubusercontent.com/12959959/63491750-e2143d00-c46c-11e9-9085-0b704126cfac.png)

Implement API endpoint search. Send a search term to the backend to have a more comprehensive search results page: 
![Screen Shot 2019-08-21 at 11 38 12 PM](https://user-images.githubusercontent.com/12959959/63491834-10921800-c46d-11e9-8661-ce6acecfd68f.png)

Ask Selina for details on the UI
