### ISSUE TITLE
[Invoice] Update navigation 

### ISSUE THREAD

**Issue by CalvinFronda** [omou-org/front-end#735]
# Update navigation 

### User story 

* PAY-APR-4
* PAY-P-25

## TODO

- [x] Update Navigation: new route to “/invoice” needs to be created that leads to a new Invoices.js view

- [x] Update Navigation bar to say “Invoices” on receptionist, admin, and parent portals. These should link to /invoices => Invoices.js

**Comment by dhuangg** [comment]
pending https://github.com/omou-org/front-end/pull/666 to see if rest of payment routes have been converted to invoice routes
