### ISSUE TITLE
Time selector

### ISSUE THREAD

**Issue by dhuangg** [omou-org/front-end#76]
Replicate this feature. It will get teacher availabilities, session duration, and days on which the session will occur to generate available time slots that a new course can be scheduled. This will save the time/dates that the user entered into the form for the eventual post request.

**DIFFERENCE FOR TUTORING** for a 1-on-1 session, this will ask the user the number of sessions they'd like to to book starting from some date.

Teacher Availabilities
![Screen Shot 2019-08-21 at 11 27 04 PM](https://user-images.githubusercontent.com/12959959/63491097-35858b80-c46b-11e9-8543-f8ef39e5b6c9.png)

Scheduling a course
![Screen Shot 2019-08-21 at 11 27 57 PM](https://user-images.githubusercontent.com/12959959/63491165-5bab2b80-c46b-11e9-9117-0c2c48dcc174.png)

Calendar based course scheduling tool
![Screen Shot 2019-08-21 at 11 28 43 PM](https://user-images.githubusercontent.com/12959959/63491211-767da000-c46b-11e9-888c-2c68050b6c7a.png)

**Comment by NeilAllavarpu** [comment]
Can be basic for Oct. 1

**Comment by NeilAllavarpu** [comment]
Do we still need this component or is instructor conflict detection enough?
