### ISSUE TITLE
Implement Cards view for Accounts

### ISSUE THREAD

**Issue by dhuangg** [omou-org/front-end#85]
There's a list and a card view for the account landing page. Right now only the list view is styled. We need to style/implement the cards.
![Screen Shot 2019-08-21 at 11 58 51 PM](https://user-images.githubusercontent.com/12959959/63493120-ba72a400-c46f-11e9-92eb-aa0e6714b36d.png)

**Comment by NeilAllavarpu** [comment]
Icons and text are a bit packed together on 13 inch screens
<img width="788" alt="Screen Shot 2019-09-15 at 16 05 02" src="https://user-images.githubusercontent.com/13577797/64928881-fc72d980-d7d2-11e9-8122-d519bab3c901.png">
Things are overlapping heavily on tablets
<img width="549" alt="Screen Shot 2019-09-15 at 16 05 09" src="https://user-images.githubusercontent.com/13577797/64928882-fda40680-d7d2-11e9-91b4-3e09e6841270.png">
Icons are on the wrong lines on mobile.
<img width="308" alt="Screen Shot 2019-09-15 at 16 05 18" src="https://user-images.githubusercontent.com/13577797/64928883-fed53380-d7d2-11e9-80fb-a51376f8cb20.png">
