### ISSUE TITLE
Implement Automated Testing

### ISSUE THREAD

**Issue by dhuangg** [omou-org/front-end#93]
Automated testing for CI/CD
[Automated Testing React Apps with Jest and Puppeteer](https://blog.logrocket.com/end-to-end-testing-react-apps-with-puppeteer-and-jest-ce2f414b4fd7/)
[React Jest Documentation](https://reactjs.org/docs/testing.html)
[Jest Tutorial](https://jestjs.io/docs/en/tutorial-react)

**Comment by CalvinFronda** [comment]
Started the boiler plate in #139.

**Comment by CalvinFronda** [comment]
I've started a google doc with basic tests I need to code out. If you need to add more tests you can edit the page. 
https://docs.google.com/document/d/1E0AiD6bcMO8mizCJCPjoQcL03bG3sk_HQvf32k8Uo88/edit?usp=sharing
